CREATE FUNCTION TRUYXUAT_DULIEU_SP () RETURNS TABLE 
AS 
RETURN (SELECT*FROM SANPHAM)
GO 

SELECT * FROM TRUYXUAT_DULIEU_SP()
GO 

CREATE FUNCTION TRUYXUAT_DULIEU_NV () RETURNS TABLE 
AS
RETURN (SELECT *FROM NHANVIEN)
GO 

SELECT * FROM TRUYXUAT_DULIEU_NV()
GO 

CREATE FUNCTION TRUYXUAT_DULIEU_KH () RETURNS TABLE 
AS
RETURN (SELECT * FROM KHACHHANG )
GO 

SELECT * FROM TRUYXUAT_DULIEU_KH()
GO 

CREATE FUNCTION TRUYXUAT_DULIEU_TP () RETURNS TABLE 
AS 
RETURN (SELECT *FROM THANHPHO )
GO
 
 SELECT * FROM TRUYXUAT_DULIEU_TP()
GO 

 CREATE FUNCTION TRUYXUAT_DULIEU_HD () RETURNS TABLE 
 AS 
 RETURN (SELECT *FROM HOADON )
 GO 

 SELECT * FROM TRUYXUAT_DULIEU_HD()
GO 

 CREATE FUNCTION TRUYXUAT_DULIEU_CTHD () RETURNS TABLE 
 AS
 RETURN (SELECT * FROM CHITIETHD)
 GO 

 SELECT * FROM TRUYXUAT_DULIEU_CTHD()
GO 