create database QLBH 
GO 
USE QLBH
GO
--DROP DATABASE QLBH 
GO 
CREATE TABLE SANPHAM (
 MASP CHAR (6) PRIMARY KEY ,
 TENSP  NVARCHAR (20),
 DVTINH CHAR (10) ,
 DONGIA MONEY ,
 HINH NVARCHAR(225)	

)
GO
CREATE TABLE NHANVIEN (
 MANV CHAR (6) PRIMARY KEY ,
 HO  NVARCHAR (20),
 TEN  NVARCHAR (20),
 NU CHAR (10) ,
 NGAYNV DATETIME ,
 DCHI NVARCHAR (225),
 DTH  NVARCHAR (10),
 HINH NVARCHAR (225)

)
GO 

CREATE TABLE THANHPHO 
( MATP CHAR (6) PRIMARY KEY ,
  TENTP NVARCHAR (20)
)
GO 

CREATE TABLE KHACHHANG (
MAKH CHAR (6) PRIMARY KEY ,
DCHI NVARCHAR (225),
TENCTY NVARCHAR (225),
TP CHAR (6) NOT NULL ,
DTH NVARCHAR (10)
CONSTRAINT PK_KH_TP FOREIGN KEY (TP) REFERENCES THANHPHO (MATP)

)
GO

CREATE TABLE HOADON (MAHD CHAR (6) PRIMARY KEY  
, MAKH CHAR (6) NOT NULL , MANV CHAR (6) NOT NULL ,
NGAYLAPHD DATETIME , NGAYNHANHANG DATETIME 
CONSTRAINT PK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
CONSTRAINT PK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
)
GO 

CREATE TABLE CHITIETHD (MAHD CHAR (6) NOT NULL  , MASP CHAR(6 ) NOT NULL , SL INT,
CONSTRAINT FK_CTHD PRIMARY KEY (MAHD , MASP),
CONSTRAINT PK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD),
CONSTRAINT PK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
)
GO

-- RÀNG BUỘC DỮ LIỆU 
-- RÀNG BUỘC DUY NHẤT
ALTER TABLE SANPHAM 
ADD CONSTRAINT UN_TENSP UNIQUE (TENSP)
GO 
-- RÀNG BUỘC MIỀN GIÁ TRỊ 
ALTER TABLE CHITIETHD 
ADD CONSTRAINT CK_SL  CHECK (SL >= 0 )
GO 

ALTER TABLE NHANVIEN 
ADD CONSTRAINT CK_NU CHECK (NU = 'NAM' OR NU = 'NU')
GO 

ALTER TABLE SANPHAM 
ADD CONSTRAINT CK_DONGIA  CHECK (DONGIA >= 1000)
GO 
-- RÀNG BUỘC MẶC ĐỊNH 
ALTER TABLE CHITIETHD 
ADD CONSTRAINT DF_SL DEFAULT 1 FOR SL
GO 
ALTER TABLE SANPHAM 
ADD CONSTRAINT DF_DV DEFAULT 'Kg' FOR DVTINH
GO 

ALTER TABLE SANPHAM 
ADD CONSTRAINT DF_DG DEFAULT '1000' FOR DONGIA 
GO

ALTER TABLE NHANVIEN 
ADD CONSTRAINT DF_NU DEFAULT 'NU' FOR NU 
GO 

SET DATEFORMAT DMY 
GO 
ALTER TABLE NHANVIEN 
ADD CONSTRAINT DF_NGAYNV DEFAULT CURRENT_TIMESTAMP FOR NGAYNV
GO 