/*CREATE FUNCTION TRUY_XUAT_DULIEU (@TENBANG NVARCHAR (20)) RETURNS TABLE AS

declare @ten nvarchar = @TENBANG 
 IF(@TENBANG = N'khoa' or @TENBANG = N'KHOA')
Begin
 RETURN (SELECT MAKHOA , TENKHOA 
 FROM KHOA	
 )
end 
 else if (@TENBANG = N'sinh viên' or @TENBANG = N'SINH VIÊN') 
Begin
 RETURN (SELECT * FROM SINHVIEN	 )
end 
else if (@TENBANG = N'môn học' or @TENBANG = N'MÔN HỌC') 
Begin
 RETURN (SELECT * FROM MONHOC) 
end 
else if (@TENBANG = N'kết quả' or @TENBANG = N'KẾT QUẢ') 
Begin
RETURN (SELECT * FROM KETQUA)	
end 

*/

CREATE FUNCTION TRUY_XUAT_DULIEUKHOA () RETURNS TABLE AS

return ( select MAKHOA , TENKHOA
from KHOA )
GO
select * from TRUY_XUAT_DULIEUKHOA()
GO
CREATE FUNCTION TRUY_XUAT_DULIEUSINHVIEN  () RETURNS TABLE AS
RETURN (SELECT *
FROM SINHVIEN)
GO
SELECT * FROM TRUY_XUAT_DULIEUSINHVIEN()
GO

CREATE FUNCTION TRUY_VAN_DULIEUMONHOC () RETURNS TABLE AS 
RETURN (SELECT * FROM MONHOC)
GO
SELECT * FROM TRUY_VAN_DULIEUMONHOC()
GO

CREATE FUNCTION TRUY_XUAT_DULIEUKETQUA () RETURNS TABLE AS 
RETURN (SELECT * FROM KETQUA)
GO 
SELECT * FROM TRUY_XUAT_DULIEUKETQUA()
GO