CREATE PROC SP_TRUYXUATKHOA 
AS  
SELECT * FROM KHOA	 

--EXEC SP_TRUYXUATKHOA
GO 
CREATE PROC SP_TRUYXUATMONHOC
AS  
SELECT * FROM MONHOC 

--EXEC SP_TRUYXUATMONHOC
GO 
CREATE PROC SP_TRUYXUATSINHVIEN 
AS  
SELECT * FROM SINHVIEN	 

--EXEC SP_TRUYXUATSINHVIEN
GO 
CREATE PROC SP_TRUYXUATKETQUA 
AS  
SELECT * FROM KETQUA	 

--EXEC SP_TRUYXUATKETQUA
GO 


--- LUA CHON MENU 
CREATE PROC SP_TRUYXUAT (@TENBANG NVARCHAR (20))
AS 
IF(@TENBANG = N'khoa' or @TENBANG = N'KHOA')
Begin
SELECT * FROM KHOA	
end 
 else if (@TENBANG = N'sinh viên' or @TENBANG = N'SINH VIÊN') 
Begin
SELECT * FROM SINHVIEN	 
end 
else if (@TENBANG = N'môn học' or @TENBANG = N'MÔN HỌC') 
Begin
SELECT * FROM MONHOC 
end 
else if (@TENBANG = N'kết quả' or @TENBANG = N'KẾT QUẢ') 
Begin
SELECT * FROM KETQUA	
end 

EXEC SP_TRUYXUAT N'KẾT QUẢ'

